In [1]:
import pandas as pd

In [2]:
CCTV_Seoul = pd.read_csv('data/서울시 자치구 년도별 CCTV 설치 현황.csv', encoding='euc-kr', thousands = ',')
CCTV_Seoul.head()

구분     총계  2013년 이전\n설치된 CCTV  2013년  2014년  2015년  2016년  2017년  2018년   
0    계  91341                2804   3097   3981   6576   8850  11566  11024  \
1  종로구   1980                  36    540    107    161    131    158    152   
2  중 구   2584                 130     87     77    236    240    372    386   
3  용산구   2847                  44     50     68     83    295    491    115   
4  성동구   4047                  58     99    110    366    279    945    459   

   2019년  ...  Unnamed: 16374  Unnamed: 16375  Unnamed: 16376  Unnamed: 16377   
0  13151  ...             NaN             NaN             NaN             NaN  \
1     69  ...             NaN             NaN             NaN             NaN   
2    155  ...             NaN             NaN             NaN             NaN   
3    322  ...             NaN             NaN             NaN             NaN   
4    647  ...             NaN             NaN             NaN             NaN   

   Unnamed: 16378  Unnamed: 16379  Unnamed: 16380  Unnamed: 16381   
0             NaN             NaN             NaN             NaN  \
1             NaN             NaN             NaN             NaN   
2             NaN             NaN             NaN             NaN   
3             NaN             NaN             NaN             NaN   
4             NaN             NaN             NaN             NaN   

   Unnamed: 16382  Unnamed: 16383  
0             NaN             NaN  
1             NaN             NaN  
2             NaN             NaN  
3             NaN             NaN  
4             NaN             NaN  

[5 rows x 16384 columns]

In [3]:
CCTV_Seoul = CCTV_Seoul[['구분', '총계', '2013년 이전\n설치된 CCTV', '2013년', '2014년', '2015년', '2016년']]
CCTV_Seoul.head()

구분     총계  2013년 이전\n설치된 CCTV  2013년  2014년  2015년  2016년
0    계  91341                2804   3097   3981   6576   8850
1  종로구   1980                  36    540    107    161    131
2  중 구   2584                 130     87     77    236    240
3  용산구   2847                  44     50     68     83    295
4  성동구   4047                  58     99    110    366    279

In [4]:
CCTV_Seoul.columns = ['구분', '총계', '2013년 이전', '2013년', '2014년', '2015년', '2016년']
CCTV_Seoul.head()

구분     총계  2013년 이전  2013년  2014년  2015년  2016년
0    계  91341      2804   3097   3981   6576   8850
1  종로구   1980        36    540    107    161    131
2  중 구   2584       130     87     77    236    240
3  용산구   2847        44     50     68     83    295
4  성동구   4047        58     99    110    366    279

In [5]:
pop_Seoul = pd.read_csv('data/서울시 주민등록인구.csv', skiprows=1)
pop_Seoul.head()

동별(1) 동별(2)  세대 (세대)        계      한국인   등록외국인  세대당인구  65세이상고령자  세대 (세대).1   
0    합계    소계  4446296  9667669  9428372  239297   2.12   1667411    4463385  \
1    합계   종로구    72524   152211   141379   10832   1.95     27958      72679   
2    합계    중구    63139   130785   120437   10348   1.91     25055      63862   
3    합계   용산구   109805   233284   218650   14634   1.99     39037     109735   
4    합계   성동구   133305   288234   281000    7234   2.11     47720     133513   

       계.1    한국인.1  등록외국인.1  세대당인구.1  65세이상고령자.1  
0  9668008  9426404   241604     2.11     1690961  
1   152212   141060    11152     1.94       28265  
2   131390   120963    10427     1.89       25353  
3   232482   217756    14726     1.98       39478  
4   287240   280240     7000     2.10       48238

In [6]:
pop_Seoul = pop_Seoul[['동별(2)', '계', '한국인', '등록외국인', '65세이상고령자']]
pop_Seoul.head()

동별(2)        계      한국인   등록외국인  65세이상고령자
0    소계  9667669  9428372  239297   1667411
1   종로구   152211   141379   10832     27958
2    중구   130785   120437   10348     25055
3   용산구   233284   218650   14634     39037
4   성동구   288234   281000    7234     47720

In [7]:
pop_Seoul.columns = ['구분', '총계', '내국인', '외국인', '고령자']
pop_Seoul.head()

구분       총계      내국인     외국인      고령자
0   소계  9667669  9428372  239297  1667411
1  종로구   152211   141379   10832    27958
2   중구   130785   120437   10348    25055
3  용산구   233284   218650   14634    39037
4  성동구   288234   281000    7234    47720

In [8]:
CCTV_Seoul = CCTV_Seoul[CCTV_Seoul.구분 != '계']
CCTV_Seoul = CCTV_Seoul.astype({'2013년 이전':int, '2013년':int, '2014년':int, '2015년':int, '2016년':int})
CCTV_Seoul.head()

구분    총계  2013년 이전  2013년  2014년  2015년  2016년
1  종로구  1980        36    540    107    161    131
2  중 구  2584       130     87     77    236    240
3  용산구  2847        44     50     68     83    295
4  성동구  4047        58     99    110    366    279
5  광진구  3480       507     82     84     64     21

In [9]:
CCTV_Seoul['총계'] = CCTV_Seoul.iloc[:, 2:].sum(axis=1)
CCTV_Seoul.head()

구분   총계  2013년 이전  2013년  2014년  2015년  2016년
1  종로구  975        36    540    107    161    131
2  중 구  770       130     87     77    236    240
3  용산구  540        44     50     68     83    295
4  성동구  912        58     99    110    366    279
5  광진구  758       507     82     84     64     21

In [10]:
CCTV_Seoul.sort_values(by='총계', ascending=True).head(5)

구분   총계  2013년 이전  2013년  2014년  2015년  2016년
9   강북구  315         0     21     16     68    210
10  도봉구  359       103      2     79     72    103
18  금천구  537         0      0     43    361    133
3   용산구  540        44     50     68     83    295
24  송파구  634        84     78     88    221    163

In [11]:
CCTV_Seoul.sort_values(by='총계', ascending=False).head(5)

구분    총계  2013년 이전  2013년  2014년  2015년  2016년
23  강남구  2815        59     62    573    826   1295
21  관악구  2052       362    244    302    537    607
8   성북구  1452       137    170    229    322    594
22  서초구  1307        74     86     70    559    518
12  은평구  1277        17     44    332    329    555

In [12]:
CCTV_Seoul['최근증가율'] = (CCTV_Seoul['2016년'] + CCTV_Seoul['2015년'] + CCTV_Seoul['2014년'] + CCTV_Seoul['2013년'] / CCTV_Seoul['2013년 이전'] * 100)
CCTV_Seoul.sort_values(by='최근증가율', ascending=False).head()

구분    총계  2013년 이전  2013년  2014년  2015년  2016년        최근증가율
9   강북구   315         0     21     16     68    210          inf
23  강남구  2815        59     62    573    826   1295  2799.084746
1   종로구   975        36    540    107    161    131  1899.000000
17  구로구  1213        37    361    193    269    353  1790.675676
21  관악구  2052       362    244    302    537    607  1513.403315

In [13]:
pop_Seoul.drop([0], inplace=True)
pop_Seoul.head()

구분      총계     내국인    외국인    고령자
1  종로구  152211  141379  10832  27958
2   중구  130785  120437  10348  25055
3  용산구  233284  218650  14634  39037
4  성동구  288234  281000   7234  47720
5  광진구  351252  337416  13836  54071

In [14]:
pop_Seoul['구분'].unique()

array(['종로구', '중구', '용산구', '성동구', '광진구', '동대문구', '중랑구', '성북구', '강북구',
       '도봉구', '노원구', '은평구', '서대문구', '마포구', '양천구', '강서구', '구로구', '금천구',
       '영등포구', '동작구', '관악구', '서초구', '강남구', '송파구', '강동구'], dtype=object)

In [15]:
pop_Seoul['외국인비율'] = pop_Seoul['외국인'] / pop_Seoul['총계'] * 100
pop_Seoul['고령자비율'] = pop_Seoul['고령자'] / pop_Seoul['총계'] * 100
pop_Seoul.head()

구분      총계     내국인    외국인    고령자     외국인비율      고령자비율
1  종로구  152211  141379  10832  27958  7.116437  18.367923
2   중구  130785  120437  10348  25055  7.912222  19.157396
3  용산구  233284  218650  14634  39037  6.273041  16.733681
4  성동구  288234  281000   7234  47720  2.509766  16.555993
5  광진구  351252  337416  13836  54071  3.939052  15.393791

In [16]:
pop_Seoul.sort_values(by='총계', ascending=False).head()

구분      총계     내국인    외국인     고령자     외국인비율      고령자비율
24  송파구  664514  658801   5713  103573  0.859726  15.586278
16  강서구  574638  569166   5472   97128  0.952252  16.902467
23  강남구  534103  529102   5001   81715  0.936336  15.299483
11  노원구  508014  503734   4280   92040  0.842496  18.117611
21  관악구  501226  486752  14474   82447  2.887719  16.449067

In [17]:
pop_Seoul.sort_values(by='외국인', ascending=False).head()

구분      총계     내국인    외국인    고령자     외국인비율      고령자비율
17   구로구  418418  395315  23103  75890  5.521512  18.137365
19  영등포구  398085  375675  22410  64810  5.629451  16.280443
6   동대문구  353601  336644  16957  64468  4.795518  18.231849
3    용산구  233284  218650  14634  39037  6.273041  16.733681
21   관악구  501226  486752  14474  82447  2.887719  16.449067

In [18]:
pop_Seoul.sort_values(by='외국인비율', ascending=False).head()

구분      총계     내국인    외국인    고령자     외국인비율      고령자비율
2     중구  130785  120437  10348  25055  7.912222  19.157396
1    종로구  152211  141379  10832  27958  7.116437  18.367923
3    용산구  233284  218650  14634  39037  6.273041  16.733681
19  영등포구  398085  375675  22410  64810  5.629451  16.280443
17   구로구  418418  395315  23103  75890  5.521512  18.137365

In [19]:
pop_Seoul.sort_values(by='고령자', ascending=False).head()

구분      총계     내국인    외국인     고령자     외국인비율      고령자비율
24  송파구  664514  658801   5713  103573  0.859726  15.586278
16  강서구  574638  569166   5472   97128  0.952252  16.902467
11  노원구  508014  503734   4280   92040  0.842496  18.117611
12  은평구  470602  466746   3856   89650  0.819376  19.050068
21  관악구  501226  486752  14474   82447  2.887719  16.449067

In [20]:
pop_Seoul.sort_values(by='고령자비율', ascending=False).head()

구분      총계     내국인    외국인    고령자     외국인비율      고령자비율
9   강북구  297702  293660   4042  66307  1.357734  22.272944
10  도봉구  313989  311694   2295  66998  0.730917  21.337690
7   중랑구  390140  385318   4822  74920  1.235967  19.203363
2    중구  130785  120437  10348  25055  7.912222  19.157396
12  은평구  470602  466746   3856  89650  0.819376  19.050068

In [21]:
data_result = pd.merge(CCTV_Seoul, pop_Seoul, on='구분')
data_result.head()

구분  총계_x  2013년 이전  2013년  2014년  2015년  2016년        최근증가율    총계_y   
0   종로구   975        36    540    107    161    131  1899.000000  152211  \
1   용산구   540        44     50     68     83    295   559.636364  233284   
2   성동구   912        58     99    110    366    279   925.689655  288234   
3   광진구   758       507     82     84     64     21   185.173570  351252   
4  동대문구   926         1      4     12    107    802  1321.000000  353601   

      내국인    외국인    고령자     외국인비율      고령자비율  
0  141379  10832  27958  7.116437  18.367923  
1  218650  14634  39037  6.273041  16.733681  
2  281000   7234  47720  2.509766  16.555993  
3  337416  13836  54071  3.939052  15.393791  
4  336644  16957  64468  4.795518  18.231849

In [22]:
del data_result['2013년 이전']
del data_result['2013년']
del data_result['2014년']
del data_result['2015년']
del data_result['2016년']
data_result.head()

구분  총계_x        최근증가율    총계_y     내국인    외국인    고령자     외국인비율      고령자비율
0   종로구   975  1899.000000  152211  141379  10832  27958  7.116437  18.367923
1   용산구   540   559.636364  233284  218650  14634  39037  6.273041  16.733681
2   성동구   912   925.689655  288234  281000   7234  47720  2.509766  16.555993
3   광진구   758   185.173570  351252  337416  13836  54071  3.939052  15.393791
4  동대문구   926  1321.000000  353601  336644  16957  64468  4.795518  18.231849

In [25]:
data_result.columns = ['구분', '총계', '최근증가율', '인구수', '내국인', '외국인', '고령자', '외국인비율', '고령자비율']
data_result.head()

구분   총계        최근증가율     인구수     내국인    외국인    고령자     외국인비율      고령자비율
0   종로구  975  1899.000000  152211  141379  10832  27958  7.116437  18.367923
1   용산구  540   559.636364  233284  218650  14634  39037  6.273041  16.733681
2   성동구  912   925.689655  288234  281000   7234  47720  2.509766  16.555993
3   광진구  758   185.173570  351252  337416  13836  54071  3.939052  15.393791
4  동대문구  926  1321.000000  353601  336644  16957  64468  4.795518  18.231849

In [26]:
data_result.set_index('구분', inplace=True)
data_result.head()

총계        최근증가율     인구수     내국인    외국인    고령자     외국인비율      고령자비율
구분                                                                       
종로구   975  1899.000000  152211  141379  10832  27958  7.116437  18.367923
용산구   540   559.636364  233284  218650  14634  39037  6.273041  16.733681
성동구   912   925.689655  288234  281000   7234  47720  2.509766  16.555993
광진구   758   185.173570  351252  337416  13836  54071  3.939052  15.393791
동대문구  926  1321.000000  353601  336644  16957  64468  4.795518  18.231849

In [27]:
import numpy as np
np.corrcoef(data_result['고령자비율'], data_result['총계'])

array([[ 1.        , -0.39436584],
       [-0.39436584,  1.        ]])

In [28]:
np.corrcoef(data_result['외국인비율'], data_result['총계'])

array([[ 1.       , -0.1299142],
       [-0.1299142,  1.       ]])

In [29]:
np.corrcoef(data_result['인구수'], data_result['총계'])

array([[1.        , 0.39720339],
       [0.39720339, 1.        ]])

In [30]:
data_result.sort_values(by='총계', ascending=False).head()

총계        최근증가율     인구수     내국인    외국인    고령자     외국인비율      고령자비율
구분                                                                       
강남구  2815  2799.084746  534103  529102   5001  81715  0.936336  15.299483
관악구  2052  1513.403315  501226  486752  14474  82447  2.887719  16.449067
성북구  1452  1269.087591  441984  430397  11587  77475  2.621588  17.528915
서초구  1307  1263.216216  408451  404325   4126  62347  1.010158  15.264254
은평구  1277  1474.823529  470602  466746   3856  89650  0.819376  19.050068

In [31]:
data_result.sort_values(by='인구수', ascending=False).head()

총계        최근증가율     인구수     내국인    외국인     고령자     외국인비율      고령자비율
구분                                                                        
송파구   634   564.857143  664514  658801   5713  103573  0.859726  15.586278
강서구   689   651.059701  574638  569166   5472   97128  0.952252  16.902467
강남구  2815  2799.084746  534103  529102   5001   81715  0.936336  15.299483
노원구  1144  1112.701299  508014  503734   4280   92040  0.842496  18.117611
관악구  2052  1513.403315  501226  486752  14474   82447  2.887719  16.449067